"""empty message

Revision ID: 34c31ee0e777
Revises: ca289898beaf
Create Date: 2021-01-06 11:34:35.204073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c31ee0e777'
down_revision = 'ca289898beaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('books', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cities', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('cities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cities', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('cities', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('collections', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('collections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('collections', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('collections', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('copies', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('copies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('copies', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('copies', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creators', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('creators', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('creators', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('creators', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('locations', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('locations', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('persons', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('persons', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('publishers', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('publishers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('publishers', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('publishers', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('series', sa.Column('approuved', sa.Boolean(), nullable=True))
    op.add_column('series', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('series', sa.Column('incorrect', sa.Boolean(), nullable=True))
    op.add_column('series', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'last_modified')
    op.drop_column('series', 'incorrect')
    op.drop_column('series', 'created_at')
    op.drop_column('series', 'approuved')
    op.drop_column('publishers', 'last_modified')
    op.drop_column('publishers', 'incorrect')
    op.drop_column('publishers', 'created_at')
    op.drop_column('publishers', 'approuved')
    op.drop_column('persons', 'last_modified')
    op.drop_column('persons', 'incorrect')
    op.drop_column('persons', 'created_at')
    op.drop_column('persons', 'approuved')
    op.drop_column('locations', 'last_modified')
    op.drop_column('locations', 'incorrect')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'approuved')
    op.drop_column('creators', 'last_modified')
    op.drop_column('creators', 'incorrect')
    op.drop_column('creators', 'created_at')
    op.drop_column('creators', 'approuved')
    op.drop_column('copies', 'last_modified')
    op.drop_column('copies', 'incorrect')
    op.drop_column('copies', 'created_at')
    op.drop_column('copies', 'approuved')
    op.drop_column('collections', 'last_modified')
    op.drop_column('collections', 'incorrect')
    op.drop_column('collections', 'created_at')
    op.drop_column('collections', 'approuved')
    op.drop_column('cities', 'last_modified')
    op.drop_column('cities', 'incorrect')
    op.drop_column('cities', 'created_at')
    op.drop_column('cities', 'approuved')
    op.drop_column('books', 'last_modified')
    op.drop_column('books', 'incorrect')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'approuved')
    # ### end Alembic commands ###
