"""empty message

Revision ID: 4c6d9d994819
Revises: 098bf48905dd
Create Date: 2020-12-13 23:13:53.912632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6d9d994819'
down_revision = '098bf48905dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbnIssn', sa.String(length=13), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('origin_language', sa.String(length=32), nullable=True),
    sa.Column('pub_year', sa.String(length=32), nullable=True),
    sa.Column('first_edition', sa.String(length=64), nullable=True),
    sa.Column('periodic_num', sa.String(length=64), nullable=True),
    sa.Column('fiction', sa.Boolean(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('literary_form', sa.Enum('PO', 'PR', 'DR', name='formchoices'), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('precision', sa.Text(), nullable=True),
    sa.Column('nukat', sa.Text(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_shelf', sa.Boolean(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('remarques', sa.String(length=255), nullable=False),
    sa.Column('signature_mark', sa.String(length=32), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('A', 'T', 'R', 'I', name='bookroles'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id', 'book_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creators')
    op.drop_table('copy')
    op.drop_table('book')
    # ### end Alembic commands ###
